name: algo_explorer_api
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
  dio: ^4.0.0
  built_value: ^7.0.9
  built_collection: ^4.3.2

dev_dependencies:
  built_value_generator: ^7.0.9
  build_runner: ^1.7.1
  pedantic: ^1.8.0
  test: ^1.6.0
